### ISSUE TITLE
NSB camera efficiency calculation

### ISSUE THREAD

**Issue by GernotMaier** [gammasim/gammasim-tools#282] opened 2022-07-06 14:22 UTC
Branch calc-nsb-camera-efficiency includes a new function calcNSBRate():

https://github.com/gammasim/gammasim-tools/compare/calc-nsb-camera-efficiency

I am not entirely sure if it works as intended and what it is need for. Any suggestion what to do with this branch, or delete it?

**Comment by orelgueta** [comment] 2022-07-11 18:19
This function is very important actually. Looking at the code (it's a copy of my code from a dedicated script), it looks fine (from memory). However, I will assign this issue to myself and will check the actual values. Once I confirm it's correct, I will open a PR for this.

**Comment by orelgueta** [comment] 2022-07-14 11:57
Looking at it a little further, the reason this branch was "abandoned" is because of the two functions `getPixelActiveSolidAngle()` and `getOnAxisEffOpticalArea()` were not implemented. The issue is that these values are not in the DB. The former can probably be derived from the pixel size (which is also not an explicit parameter). The latter is calculated when we run the ray tracing.

This means that in order to solve this issue we either hardcode these values for each telescope or we create a new collection in the DB for derived values, fill it up and read them from there. @GernotMaier, which solution do you prefer? Take into account that these values are unlikely to change.

**Comment by orelgueta** [comment] 2022-07-15 11:38
With the latest commits to this branch, the `getPixelActiveSolidAngle()` point was solved without external info. 

Now we need to decide what to do about the effective mirror area and the NSB reference value which is set to 0.24 ph./(cm² ns sr everywhere. Should these go into the DB in a new collection or somewhere else?

**Comment by GernotMaier** [comment] 2022-07-15 11:55
Very good.

- NSB reference value: we will probably have a couple of reference values to be used (e.g., the NSB reference spectrum); it probably makes sense to start putting them into the DB; there should also be a way to get all reference values from the DB

- can you remind me how the effective mirror area is derived? Is this a computational intensive step, could we do it 'on the fly'?

**Comment by orelgueta** [comment] 2022-07-15 14:45
OK, will add the NSB reference value to a new collection in the DB. Perhaps I will call it "Reference_values" or something like that.

We calculate the effective mirror area through ray tracing. Not very computationally intensive, but I am not sure we want to run it each time we calculate the NSB rate. We anyway plan to save the results of the simulations in the DB, so I don't see an issue with saving also the effective mirror area curves of each telescope.

**Closed** 2022-09-07 05:24 UTC
